name: Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.DROPLET_HOST }}
        USERNAME: ${{ secrets.DROPLET_USERNAME }}
        PORT: ${{ secrets.DROPLET_PORT }}
        PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
      with:
        source: "."
        target: "/opt/app"

    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.DROPLET_HOST }}
        USERNAME: ${{ secrets.DROPLET_USERNAME }}
        PORT: ${{ secrets.DROPLET_PORT }}
        PASSWORD: ${{ secrets.DROPLET_PASSWORD }}
        #script: cat /opt/app/README.md
        script: |
          cd /opt/app
          docker-compose down
          docker-compose up --build -d