name: build

on:
  push:
    branches: 
      - master
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: execute droplet commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USERNAME }}
        password: ${{ secrets.DROPLET_PASSWORD }}
        port: ${{ secrets.DROPLET_PORT }}
        script: |
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
          docker pull aleksijaakkojuhani/vue-front
          docker run -p 8080:80 aleksijaakkojuhani/vue-front


#     - uses: actions/checkout@v2
#     - run: cd frontend && docker build -t aleksijaakkojuhani/vue-front .
#     - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#       env:
#         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
#         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
#     - run: docker push aleksijaakkojuhani/vue-front