#name: build
#
#on:
#  push:
#    branches: 
#      - master
#    paths:
#      - 'server/**'
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - run: cd server && docker build -t aleksijaakkojuhani/multi2-server .
#    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#      env:
#        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
#        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
#    - run: docker push aleksijaakkojuhani/multi2-server
#    - name: start container on droplet
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.DROPLET_HOST }}
#        username: ${{ secrets.DROPLET_USERNAME }}
#        password: ${{ secrets.DROPLET_PASSWORD }}
#        port: ${{ secrets.DROPLET_PORT }}
#        script: |
#          docker stop $(docker ps -a -q)
#          docker rm $(docker ps -a -q)
#          docker pull aleksijaakkojuhani/multi2-server
#          docker run -d -p 5000:5000 aleksijaakkojuhani/multi2-server